/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package user_manual;

import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.time.Duration;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.apache.commons.exec.ExecuteException;
import org.bouncycastle.jcajce.provider.symmetric.util.PBE.Util;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;

public class AppTest {
    WebDriver driver = null;

    @BeforeSuite
    public void initialize_driver() {
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    }

    @Test(enabled = false)
    @Parameters("irctc_first_letters")
    public void irctc_from_station(String param) throws InterruptedException {
        System.out.println("GOING TO IRCTC SITE");
        driver.get("https://www.irctc.co.in/nget/train-search");
        System.out.println("FINDING THE INPUT ELEMENT");
        WebElement from_station = driver.findElement(By.xpath(
                "//input[@class='ng-tns-c57-8 ui-inputtext ui-widget ui-state-default ui-corner-all ui-autocomplete-input ng-star-inserted']"));
        from_station.clear();
        System.out.println("SENDING KEYS");
        from_station.sendKeys(param);
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(2));
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath(
                "//div[@class='ng-trigger ng-trigger-overlayAnimation ng-tns-c57-8 ui-autocomplete-panel ui-widget ui-widget-content ui-corner-all ui-shadow ng-star-inserted']")));
        Thread.sleep(500);
        System.out.println("CLICKING ON FIRST ELEMENT");
        WebElement first_auto = driver.findElement(By.xpath(
                "//div[@class='ng-trigger ng-trigger-overlayAnimation ng-tns-c57-8 ui-autocomplete-panel ui-widget ui-widget-content ui-corner-all ui-shadow ng-star-inserted']"));
        first_auto.click();
        System.out.println("SUCCESS!");
    }

    @Test(enabled = false)
    @Parameters({ "email1", "pwd", "media_path" })
    public void linkedin_media(String email1, String pwd, String media_path) throws InterruptedException {
        driver.get("https://www.linkedin.com/home");
        driver.findElement(By.xpath("//input[@name='session_key']")).sendKeys(email1);
        driver.findElement(By.xpath("//input[@name='session_password']")).sendKeys(pwd);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        driver.findElement(By.xpath(
                "//button[@class='artdeco-button artdeco-button--muted artdeco-button--4 artdeco-button--tertiary ember-view share-box-feed-entry__trigger']"))
                .click();
        driver.findElement(By.xpath(
                "//button[@class='artdeco-button artdeco-button--circle artdeco-button--muted artdeco-button--2 artdeco-button--tertiary ember-view']"))
                .click();
        driver.findElement(By.xpath("//input[@id='image-sharing-detour-container__file-input']")).sendKeys(media_path);
        driver.findElement(By.xpath(
                "//button[@class='share-box-footer__primary-btn artdeco-button artdeco-button--2 artdeco-button--primary ember-view']"))
                .click();
        driver.findElement(By.xpath(
                "//button[@class='share-actions__primary-action artdeco-button artdeco-button--2 artdeco-button--primary ember-view']"))
                .click();
        Thread.sleep(5000);
        driver.findElement(By.xpath(
                "//button[@class='global-nav__primary-link global-nav__primary-link-me-menu-trigger artdeco-dropdown__trigger artdeco-dropdown__trigger--placement-bottom ember-view']"))
                .click();
        driver.findElement(By.xpath("//*[text()='Sign Out']")).click();
        Thread.sleep(500);
        try {
            driver.findElement(By.xpath(
                    "//button[@class='full-width mt4 artdeco-button artdeco-button--muted artdeco-button--2 artdeco-button--secondary ember-view']"))
                    .click();
            Thread.sleep(5000);
        } catch (Exception e) {
            System.out.println("No need for extra steps to log out!");
        }
    }

    @Test(enabled = false)
    @Parameters({ "email2", "pwd", "content" })
    public void linkedin_post(String email2, String pwd, String content) throws InterruptedException {
        driver.get("https://www.linkedin.com/home");
        driver.findElement(By.xpath("//input[@name='session_key']")).sendKeys(email2);
        driver.findElement(By.xpath("//input[@name='session_password']")).sendKeys(pwd);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        driver.findElement(By.xpath(
                "//button[@class='artdeco-button artdeco-button--muted artdeco-button--4 artdeco-button--tertiary ember-view share-box-feed-entry__trigger']"))
                .click();
        driver.findElement(By.xpath("//div[@aria-placeholder='What do you want to talk about?']")).sendKeys(content);
        driver.findElement(By.xpath(
                "//button[@class='share-actions__primary-action artdeco-button artdeco-button--2 artdeco-button--primary ember-view']"))
                .click();
        Thread.sleep(5000);
        driver.findElement(By.xpath(
                "//button[@class='global-nav__primary-link global-nav__primary-link-me-menu-trigger artdeco-dropdown__trigger artdeco-dropdown__trigger--placement-bottom ember-view']"))
                .click();
        driver.findElement(By.xpath("//*[text()='Sign Out']")).click();
        Thread.sleep(500);
        try {
            driver.findElement(By.xpath(
                    "//button[@class='full-width mt4 artdeco-button artdeco-button--muted artdeco-button--2 artdeco-button--secondary ember-view']"))
                    .click();
            Thread.sleep(5000);
        } catch (Exception e) {
            System.out.println("No need for extra steps to log out!");
        }
    }

    @Test(enabled = false)
    public void google_amazon() throws InterruptedException {
        driver.get("https://www.google.com");
        Thread.sleep(2000);
        driver.findElement(By.xpath("//input[@aria-label='Search']")).sendKeys("amazon", Keys.ENTER);
        System.out.println(driver.findElement(By.xpath("//a[contains(@href, 'amazon')]")) == null
                ? "Did not find AMAZON link: PASS"
                : "FOUND AMAZON LINK: PASS");
    }

    @Test(enabled = false)
    public void irctc_frames() throws InterruptedException {
        driver.get("https://the-internet.herokuapp.com/nested_frames");
        Thread.sleep(1000);
        System.out.println("total number of iFrames" + Utility.countIframes(driver));
        System.out.println("\n\n");
        System.out.println("total number of Frames" + Utility.countFrames(driver));
    }

    @Test(enabled = false)
    public void w_three_schools() throws InterruptedException {

        driver.get("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert");
        driver.switchTo().frame("iframeResult");
        driver.findElement(By.xpath("//button[text()='Try it']")).click();
        Alert alert = driver.switchTo().alert();
        Thread.sleep(1000);
        alert.accept();
        Thread.sleep(1000);

        driver.get("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open");
        String originalWindowHandle = driver.getWindowHandle();
        driver.switchTo().frame("iframeResult");
        driver.findElement(By.xpath("//button[text()='Try it']")).click();
        Thread.sleep(1000);

        for (String windowHandle : driver.getWindowHandles()) {
            if (!originalWindowHandle.equals(windowHandle)) {
                driver.switchTo().window(windowHandle);
                break;
            }
        }
        Thread.sleep(1000);
    }

    @Test(enabled = false)
    public void imdb() throws InterruptedException {
        driver.get("https://www.imdb.com/chart/top");
        System.out.println(
                "Highest rated movie is " + driver.findElement(By.xpath("//td[@class='titleColumn']")).getText());
        List<WebElement> movies = driver.findElements(By.xpath("//tbody[@class='lister-list']/tr"));
        System.out.println("Total movies on list " + movies.size());
        Select select = new Select(driver.findElement(By.xpath("//select[@id='lister-sort-by-options']")));
        select.selectByVisibleText("Release Date");
        try {
            Thread.sleep(1000);
            driver.findElement(By.xpath("//span[@class='global-sprite lister-sort-reverse ascending']")).click();
        } catch (Exception e) {
            System.out.println("Maybe already in Descending order?-->" + e);
        }
        Thread.sleep(1000);

        System.out.println(
                "Oldest Movie is " + driver.findElement(By.xpath("//tbody[@class='lister-list']/tr")).getText());
        try {
            driver.findElement(By.xpath("//span[@class='global-sprite lister-sort-reverse descending']")).click();
        } catch (Exception e) {
            System.out.println("Maybe already in Ascending order?-->" + e);
        }
        Thread.sleep(1000);

        System.out.println(
                "Newest Movie is " + driver.findElement(By.xpath("//tbody[@class='lister-list']/tr")).getText());

        select = new Select(driver.findElement(By.xpath("//select[@id='lister-sort-by-options']")));
        select.selectByVisibleText("Your Rating");
        Thread.sleep(1000);

        System.out.println(
                "Popular Movie is " + driver.findElement(By.xpath("//tbody[@class='lister-list']/tr")).getText());

    }

    @Test(enabled = false)
    public void stocks() throws InterruptedException {
        driver.get("https://finance.yahoo.com/quote/AAPL/history?p=AAPL");
        try {
            driver.findElement(By.xpath("//button[@aria-label='Close']")).click();
        } catch (Exception e) {
            System.out.println("Pop up already closed");
        }
        JavascriptExecutor js = (JavascriptExecutor) driver;

        while (true) {
            Long initialHeight = (Long) js.executeScript("return document.body.scrollHeight");
            js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
            Thread.sleep(3000);
            Long newHeight = (Long) js.executeScript("return document.body.scrollHeight");
            if (newHeight.equals(initialHeight)) {
                break;
            }
        }

    }

    @AfterSuite
    public void close_and_quit_driver() {
        driver.close();
        driver.quit();
    }
}
