/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package user_manual;

import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.time.Duration;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;

public class AppTest {
    WebDriver driver = null;
    @BeforeSuite
    public void initialize_driver(){
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    }


    @Test (enabled = false)
    @Parameters("irctc_first_letters")
    public void irctc_from_station(String param) throws InterruptedException{
        System.out.println("GOING TO IRCTC SITE");
        driver.get("https://www.irctc.co.in/nget/train-search");
        System.out.println("FINDING THE INPUT ELEMENT");
        WebElement from_station = driver.findElement(By.xpath("//input[@class='ng-tns-c57-8 ui-inputtext ui-widget ui-state-default ui-corner-all ui-autocomplete-input ng-star-inserted']"));
        from_station.clear();
        System.out.println("SENDING KEYS");
        from_station.sendKeys(param);  
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(2));
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//div[@class='ng-trigger ng-trigger-overlayAnimation ng-tns-c57-8 ui-autocomplete-panel ui-widget ui-widget-content ui-corner-all ui-shadow ng-star-inserted']")));
        Thread.sleep(500);
        System.out.println("CLICKING ON FIRST ELEMENT");
        WebElement first_auto = driver.findElement(By.xpath("//div[@class='ng-trigger ng-trigger-overlayAnimation ng-tns-c57-8 ui-autocomplete-panel ui-widget ui-widget-content ui-corner-all ui-shadow ng-star-inserted']"));
        first_auto.click();
        System.out.println("SUCCESS!");
    }

    @Test (enabled = true)
    public void linkedin_media() throws InterruptedException{
        driver.get("https://www.linkedin.com/home");
        driver.findElement(By.xpath("//input[@name='session_key']")).sendKeys("dummy.acc.3.321.3009@gmail.com");
        driver.findElement(By.xpath("//input[@name='session_password']")).sendKeys("Dummy3009@");
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        driver.findElement(By.xpath("//button[@class='artdeco-button artdeco-button--muted artdeco-button--4 artdeco-button--tertiary ember-view share-box-feed-entry__trigger']")).click();
        driver.findElement(By.xpath("//button[@class='artdeco-button artdeco-button--circle artdeco-button--muted artdeco-button--2 artdeco-button--tertiary ember-view']")).click();
        driver.findElement(By.xpath("//input[@id='image-sharing-detour-container__file-input']")).sendKeys("C:\\Users\\Atri\\Desktop\\Crio_Dark.png");
        driver.findElement(By.xpath("//button[@class='share-box-footer__primary-btn artdeco-button artdeco-button--2 artdeco-button--primary ember-view']")).click();
        driver.findElement(By.xpath("//button[@class='share-actions__primary-action artdeco-button artdeco-button--2 artdeco-button--primary ember-view']")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("//button[@class='global-nav__primary-link global-nav__primary-link-me-menu-trigger artdeco-dropdown__trigger artdeco-dropdown__trigger--placement-bottom ember-view']")).click();
        driver.findElement(By.xpath("//*[text()='Sign Out']")).click();
        Thread.sleep(5000);
    }

    @Test (enabled = true)
    public void linkedin_post() throws InterruptedException{
        driver.get("https://www.linkedin.com/home");
        driver.findElement(By.xpath("//input[@name='session_key']")).sendKeys("dummy.acc.3.321.3009@gmail.com");
        driver.findElement(By.xpath("//input[@name='session_password']")).sendKeys("Dummy3009@");
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        driver.findElement(By.xpath("//button[@class='artdeco-button artdeco-button--muted artdeco-button--4 artdeco-button--tertiary ember-view share-box-feed-entry__trigger']")).click();
        driver.findElement(By.xpath("//div[@aria-placeholder='What do you want to talk about?']")).sendKeys("Hello Automation World!");
        driver.findElement(By.xpath("//button[@class='share-actions__primary-action artdeco-button artdeco-button--2 artdeco-button--primary ember-view']")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("//button[@class='global-nav__primary-link global-nav__primary-link-me-menu-trigger artdeco-dropdown__trigger artdeco-dropdown__trigger--placement-bottom ember-view']")).click();
        driver.findElement(By.xpath("//*[text()='Sign Out']")).click();
        Thread.sleep(5000);
    }

    @Test (enabled = false)
    public void google_amazon() throws InterruptedException{
        driver.get("https://www.google.com");
        Thread.sleep(2000);
        driver.findElement(By.xpath("//input[@aria-label='Search']")).sendKeys("amazon",Keys.ENTER);
        System.out.println(driver.findElement(By.xpath("//a[contains(@href, 'amazon')]"))==null?"Did not find AMAZON link: PASS":"FOUND AMAZON LINK: PASS");
    }

    @AfterSuite
    public void close_and_quit_driver(){
        driver.close();
        driver.quit();
    }
}
